import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/theme-provider";
import TopBar from "@/components/shared/TopBar";
import SideBar from "@/components/shared/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "IMAGES",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClerkProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <main className="w-full max-w-7xl mx-auto px-2">
              <TopBar />
              <div className="flex gap-3">
                <SideBar />
                {children}
              </div>
            </main>
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
