import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/theme-provider";
import TopBar from "@/components/shared/TopBar";
import SideBar from "@/components/shared/SideBar";
import { Toaster } from "@/components/ui/toaster";
import BottomBar from "@/components/shared/BottomBar";
import { ScrollArea } from "@/components/ui/scroll-area";
import SideSheet from "@/components/shared/SideSheet";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "images",
  description: "App Generated by Next.js and made by Juan Isturiz",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.svg" sizes="any" />
      </head>
      <body className={inter.className}>
        <ClerkProvider>
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
            <ScrollArea className="h-auto sm:h-screen">
              <main className="relative">
                <div className="hidden z-40 left-2 top-2 md:fixed md:block lg:hidden">
                  <SideSheet />
                </div>
                <TopBar />
                <div className="relative flex flex-col lg:flex-row gap-3">
                  <SideBar />
                  {children}
                </div>
                <BottomBar />
              </main>
            </ScrollArea>
            <Toaster />
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
