import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/theme-provider";
import TopBar from "@/components/shared/TopBar";
import { Image } from "lucide-react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "IMAGES",
  description: "Generated by Next.js",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClerkProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <div className="w-full max-w-7xl mx-auto px-2">
              <TopBar />
              {/* <div className="flex items-center gap-2 mb-4">
                <Image size={32} />
                <h1 className="font-semibold text-3xl uppercase">images</h1>
              </div> */}
              <div className="mt-2">{children}</div>
            </div>
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
